use TN_Db
--Bảng menu
CREATE TABLE MENU(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(250),
	DESCRIPTION NVARCHAR(MAX) NULL,
	DATE_CREATED DATETIME NULL DEFAULT GETDATE(),
	CREATOR NVARCHAR(250),
)
--Bảng giới thiệu
CREATE TABLE INTRODUCE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IMAGE NVARCHAR(MAX),
	NAME NVARCHAR(250),
	DESCRIPTION NVARCHAR(MAX),
	CONTENT NVARCHAR(MAX),
	CREATOR NVARCHAR(250),
	DATE_CREATED DATETIME NULL DEFAULT GETDATE(),
)
--Bảng chuyên mục
CREATE TABLE CATEGORIES(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(250),
	DESCRIPTION NVARCHAR(MAX) NULL,
	DATE_CREATED DATETIME NULL DEFAULT GETDATE(),
	CREATED NVARCHAR(250)
)
--Bảng tin bài
CREATE TABLE NEWS_ARTICLE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
	CATEGORIES_ID INT,
	FOREIGN KEY (CATEGORIES_ID) REFERENCES CATEGORIES(ID) ,
    IMAGE NVARCHAR(MAX),
    NAME NVARCHAR(250),
    DESCRIPTION NVARCHAR(MAX) NULL,
    CONTENT NVARCHAR(MAX),
    DATE_CREATED DATETIME NULL DEFAULT GETDATE(),
    CREATED NVARCHAR(250)
)
--Bảng file(ảnh/video/..)
CREATE TABLE MORE_IMAGE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NEW_ID INT, 
	NAME_IMG NVARCHAR(250),
	DATE_CREATED DATETIME NULL DEFAULT GETDATE(),
	FOREIGN KEY (NEW_ID) REFERENCES NEWS_ARTICLE(ID) ,
)
--Bảng bình luận tin bài
CREATE TABLE COMMENT(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR(250),
EMAIL NVARCHAR(250),
CONTENT NVARCHAR(MAX),
DATE_CREATED DATETIME NULL DEFAULT GETDATE(),
)
--Bảng liên hệ
CREATE TABLE HOTLINE(
ID INT IDENTITY(1,1) PRIMARY KEY,
EMAIL NVARCHAR(250),
TEL NVARCHAR(10) NULL ,
CONTENT NVARCHAR(MAX),
DATE_CREATED DATETIME NULL DEFAULT GETDATE(),
)

--Bảng tài khoản
CREATE TABLE ACOUNT(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR(250),
ADDRESS NVARCHAR(250),
DATEOFBIRTH DATE,
EMAIL NVARCHAR(250),
USERNAME NVARCHAR(250),
PASSWORD NVARCHAR(250),
)

--Bảng Slide_show
CREATE TABLE SLIDER(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR(250),
IMAGE NVARCHAR(MAX),
CONTENT NVARCHAR(MAX) NULL,
DATE_CREATED DATETIME NULL DEFAULT GETDATE(),
)

--Bảng quảng cáo
CREATE TABLE BRAND(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR(250),
IMAGE NVARCHAR(MAX),
CONTENT NVARCHAR(MAX) NULL,
DATE_CREATED DATETIME NULL DEFAULT GETDATE(),
)

